[workspace]
members = [
    "node",
    "pallets/quadvoting",
    "runtime",
]
[profile.release]
panic = "unwind"

# Then you build using cargo build --profile=fast
[profile.fast]
inherits = "release"
opt-level = 0
lto = "off"
incremental = true
codegen-units = 256
panic = "unwind"
